"use client";

import Link from "next/link";
import { useState } from "react";

const Arrow = () => <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M3 10h13M11 5l5 5-5 5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>;
const Check = () => <svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 10 3 3 7-7" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>;

function Header() {
  return <header className="header"><Link href="/" className="brand"><span className="brand-mark"><i /></span>recoverly</Link><nav><a href="#how-it-works">How it works</a><a href="#calculator">Revenue calculator</a></nav><Link className="button button-small" href="/demo">Try the demo <Arrow /></Link></header>;
}

export default function Home() {
  const [estimates, setEstimates] = useState(80);
  const [average, setAverage] = useState(12400);
  const [rate, setRate] = useState(38);
  const annual = Math.round(estimates * average * 12 * (rate / 100) * 0.12);
  const [submitted, setSubmitted] = useState(false);
  return <main>
    <Header />
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span />Built for residential HVAC contractors</p><h1>Your replacement estimates are leaving <em>revenue behind.</em></h1><p className="hero-text">Recoverly finds the follow-up gaps, pricing inconsistencies, and stalled proposals that quietly cost your team closed jobs.</p><div className="hero-actions"><a className="button" href="#analysis">Get your free analysis <Arrow /></a><Link className="text-link" href="/demo">See it in action <span>↗</span></Link></div><p className="microcopy"><Check /> No integrations required to get started</p></div>
      <div className="hero-panel"><div className="panel-top"><span className="live-dot" /> Revenue Recovery Summary <span className="more">•••</span></div><div className="panel-body"><p className="panel-label">ESTIMATED RECOVERABLE REVENUE</p><div className="panel-total">$184,320 <span>/ year</span></div><div className="trend">↑ 14.8% <small>of current estimate revenue</small></div><div className="chart"><div className="gridline" /><div className="gridline" /><div className="gridline" /><svg viewBox="0 0 500 190" preserveAspectRatio="none"><path d="M0,155 C40,144 51,145 79,132 S124,154 154,118 S197,124 222,97 S268,116 300,75 S340,83 375,45 S426,57 500,9" fill="none" stroke="#59c3a6" strokeWidth="3" /><path d="M0,155 C40,144 51,145 79,132 S124,154 154,118 S197,124 222,97 S268,116 300,75 S340,83 375,45 S426,57 500,9 L500,190 L0,190Z" fill="url(#fill)" /><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#59c3a6" stopOpacity=".2"/><stop offset="1" stopColor="#59c3a6" stopOpacity="0"/></linearGradient></defs></svg></div><div className="panel-stats"><div><b>27</b><span>at-risk estimates</span></div><div><b>$64.2k</b><span>stalled pipeline</span></div><div><b>42%</b><span>follow-up coverage</span></div></div></div></div>
    </section>
    <section className="proof"><p>Built around the workflow of high-performing residential contractors</p><div><span>Replacement sales</span><span>Service agreements</span><span>Field operations</span><span>Revenue operations</span></div></section>
    <section className="problem section"><div className="section-intro"><p className="eyebrow">The problem</p><h2>Every missed follow-up has a cost.</h2></div><div className="problem-copy"><p>Replacement estimates carry your highest ticket values — and the most room for revenue to slip away. Most teams can see the close rate. Few can see exactly where the opportunities go cold.</p><a className="text-link dark" href="#calculator">Calculate your opportunity <Arrow /></a></div><div className="problem-grid"><article><span className="num">01</span><h3>Follow-up happens inconsistently</h3><p>Busy comfort advisors rely on personal systems. Quotes that need attention get buried.</p></article><article><span className="num">02</span><h3>At-risk estimates stay invisible</h3><p>Without a clear view, there is no practical way to prioritize the deals most likely to close.</p></article><article><span className="num">03</span><h3>Revenue recovery is reactive</h3><p>Teams review pipeline after the opportunity is gone, not while it can still be recovered.</p></article></div></section>
    <section className="how section" id="how-it-works"><div className="how-head"><p className="eyebrow">How it works</p><h2>A sharper view of every replacement opportunity.</h2><p>Recoverly gives your team the daily focus needed to follow up with intent and protect estimate revenue.</p></div><div className="steps"><article><span className="step-no">01</span><div><h3>Upload your estimate data</h3><p>Start with a simple export. No implementation project or CRM change required.</p></div></article><article><span className="step-no">02</span><div><h3>See where revenue is at risk</h3><p>Understand which estimates need attention, based on timing and engagement signals.</p></div></article><article><span className="step-no">03</span><div><h3>Give your team a daily plan</h3><p>Prioritize the right conversations, then measure the revenue you recover.</p></div></article></div></section>
    <section className="calculator section" id="calculator"><div className="calc-copy"><p className="eyebrow">Estimate your opportunity</p><h2>What could stronger follow-up be worth?</h2><p>Use fictional inputs to model the potential impact of recovering 12% of your currently lost replacement revenue.</p><div className="formula"><span>Monthly estimates</span><b>×</b><span>Average ticket</span><b>×</b><span>Lost close rate</span></div></div><div className="calc-card"><label>Replacement estimates per month <output>{estimates}</output><input type="range" min="20" max="200" value={estimates} onChange={e => setEstimates(+e.target.value)} /></label><label>Average replacement ticket <output>${average.toLocaleString()}</output><input type="range" min="6000" max="25000" step="100" value={average} onChange={e => setAverage(+e.target.value)} /></label><label>Current close rate <output>{rate}%</output><input type="range" min="15" max="70" value={rate} onChange={e => setRate(+e.target.value)} /></label><div className="calc-result"><span>Potential annual revenue recovered</span><strong>${annual.toLocaleString()}</strong><small>Illustrative estimate only · based on fictional benchmarks</small></div></div></section>
    <section className="demo-band"><div><p className="eyebrow light">Interactive demo</p><h2>See which estimates deserve a second look.</h2><p>Explore a sample recovery workspace and see how a sales manager prioritizes the day.</p></div><Link href="/demo" className="button button-white">Open interactive demo <Arrow /></Link></section>
    <section className="analysis section" id="analysis"><div><p className="eyebrow">Free revenue recovery analysis</p><h2>Find the revenue already in your pipeline.</h2><p>Share a few details about your replacement business. We’ll return a practical snapshot of where to focus first.</p></div><form onSubmit={e => { e.preventDefault(); setSubmitted(true); }}><div className="form-row"><label>First name<input required placeholder="Jordan" /></label><label>Work email<input required type="email" placeholder="jordan@company.com" /></label></div><label>Company name<input required placeholder="Summit Heating & Air" /></label><button className="button" type="submit">Request my analysis <Arrow /></button>{submitted && <p className="success">Thanks — your fictional request has been captured.</p>}<p className="form-note">By submitting, you agree to receive information from Recoverly. No spam.</p></form></section>
    <footer><Link href="/" className="brand"><span className="brand-mark"><i /></span>recoverly</Link><p>Revenue recovery for residential HVAC estimates.</p><span>© 2026 Recoverly, Inc. Fictional product.</span></footer>
  </main>;
}
